#!/usr/bin/env python3
"""gen_fast12_scalar.py -- train a naive 16-pixel FAST-12 ID3 tree (no
cardinal/SIMD priors) on exhaustive 2^16 configs and emit the Rust trees
module for src/fast.rs. Usage: gen_fast12_scalar.py [-o fast12_trees.rs]"""

import math
import sys
import time

N = 16

# RUN[i] = the 12 circle pixels i..i+11 (mod 16) of the exact FAST-12 rule.
RUN = []
for i in range(N):
    m = 0
    for j in range(12):
        m |= 1 << ((i + j) % N)
    RUN.append(m)


def is_corner(mask):
    for rm in RUN:
        if (mask & rm) == rm:
            return True
    return False


# Exhaustive labels, precomputed once; configs are plain 16-bit mask ints.
LABELS = [is_corner(m) for m in range(1 << N)]

# (dx, dy) circle offsets in fast.c make_offsets() order; training bit k ==
# table index k. Shared with the emitted CIRCLE const.
CIRCLE_DXDY = [
    (0, 3), (1, 3), (2, 2), (3, 1), (3, 0), (3, -1), (2, -2), (1, -3),
    (0, -3), (-1, -3), (-2, -2), (-3, -1), (-3, 0), (-3, 1), (-2, 2), (-1, 3),
]


def entropy(c0, c1):
    n = c0 + c1
    h = 0.0
    for c in (c0, c1):
        if c:
            p = c / n
            h -= p * math.log2(p)
    return h


def id3(configs):
    """Classic ID3 over the 16 circle pixels; ("leaf", l) | ("node", f, c0, c1)."""
    cnt = [0, 0]
    for m in configs:
        cnt[LABELS[m]] += 1
    if cnt[0] == 0:
        return ("leaf", 1)
    if cnt[1] == 0:
        return ("leaf", 0)
    h = entropy(cnt[0], cnt[1])
    best, gain = -1, 0.0
    for f in range(N):
        t = [[0, 0], [0, 0]]
        for m in configs:
            t[(m >> f) & 1][LABELS[m]] += 1
        s0 = t[0][0] + t[0][1]
        s1 = len(configs) - s0
        if s0 and s1:
            g = h - (s0 * entropy(t[0][0], t[0][1]) + s1 * entropy(t[1][0], t[1][1])) / len(configs)
            if g > gain:  # ascending f, strict >: ties keep the lowest index
                best, gain = f, g
    assert best != -1, "impure node with no informative feature"
    c0 = [m for m in configs if ((m >> best) & 1) == 0]
    c1 = [m for m in configs if (m >> best) & 1]
    return ("node", best, id3(c0), id3(c1))


def eval_tree(node, mask):
    while node[0] != "leaf":
        node = node[3] if (mask >> node[1]) & 1 else node[2]
    return node[1]


def stats(node):
    if node[0] == "leaf":
        return 1, 0
    n0, d0 = stats(node[2])
    n1, d1 = stats(node[3])
    return 1 + n0 + n1, 1 + max(d0, d1)


def emit_rust(node, pad, op, out):
    if node[0] == "leaf":
        out.write(f"{pad}return {'true' if node[1] else 'false'};\n")
        return
    _, f, c0, c1 = node
    out.write(f"{pad}if (p[(c + off[{f}]) as usize] as i32) {op} thr {{\n")
    emit_rust(c1, pad + "    ", op, out)
    out.write(f"{pad}}} else {{\n")
    emit_rust(c0, pad + "    ", op, out)
    out.write(f"{pad}}}\n")


def write_rust_module(tree, out):
    out.write("/* fast12_trees.rs -- GENERATED by gen_fast12_scalar.py, do not edit.\n")
    out.write(" * Regenerate: python3 scripts/gen_fast12_scalar.py -o src/fast12_trees.rs\n")
    out.write(" * Naive 16-pixel FAST-12 ID3 trees, no cardinal/SIMD priors; included by src/fast.rs. */\n\n")
    out.write("/// (dx, dy) circle offsets, fast.c make_offsets() order (offset = dx + dy*stride).\n")
    out.write("pub const CIRCLE: [(i32, i32); 16] = [\n    ")
    out.write(", ".join(f"({dx}, {dy})" for dx, dy in CIRCLE_DXDY))
    out.write(",\n];\n\n")
    out.write("/// Light: 12 contiguous circle px strictly > thr (thr = center + b).\n")
    out.write("#[inline(always)]\npub fn light(p: &[u8], c: isize, off: &[isize; 16], thr: i32) -> bool {\n")
    emit_rust(tree, "    ", ">", out)
    out.write("}\n\n")
    out.write("/// Dark: light's mirror, strictly < thr (thr = center - b).\n")
    out.write("#[inline(always)]\npub fn dark(p: &[u8], c: isize, off: &[isize; 16], thr: i32) -> bool {\n")
    emit_rust(tree, "    ", "<", out)
    out.write("}\n")


def main():
    args = sys.argv[1:]
    if args in (["-h"], ["--help"]):
        print(__doc__)
        return
    out_path = args[1] if len(args) == 2 and args[0] == "-o" else None
    if out_path is None and args:
        print("usage: python3 scripts/gen_fast12_scalar.py [-o src/fast12_trees.rs]",
              file=sys.stderr)
        sys.exit(2)

    t0 = time.time()
    tree = id3(list(range(1 << N)))
    t_train = time.time() - t0
    for m in range(1 << N):
        assert eval_tree(tree, m) == LABELS[m], f"self-check failed on mask {m:#06x}"
    nodes, depth = stats(tree)
    print(f"tree {nodes} nodes, depth {depth}, {sum(LABELS)}/{1 << N} masks are corners; "
          f"trained in {t_train:.1f}s; self-check passed (both polarities, all masks)",
          file=sys.stderr)

    out = open(out_path, "w") if out_path else sys.stdout
    write_rust_module(tree, out)
    if out_path:
        out.close()
        print(f"emitted {out_path} ({nodes} tree nodes)", file=sys.stderr)


if __name__ == "__main__":
    main()
