#!/usr/bin/env python3
"""Write map.txt from a COLMAP run (adapted from slam-exp build_map.py):
CAMERA line with the refined SIMPLE_RADIAL params (f cx cy k1), per-image
POSE lines, and POINT x y z <hex64> map points deduped by 3D position."""

import argparse
import csv as csv_mod
from pathlib import Path

import numpy as np
import pycolmap


def load_descriptors(features_dir: Path):
    """stem -> list of 64-char hex descriptor strings (row order = feature idx)."""
    descs = {}
    for csv_path in sorted(features_dir.glob("*.csv")):
        with open(csv_path) as f:
            rows = [[c.strip() for c in r] for r in csv_mod.reader(f) if r]
        descs[csv_path.stem] = [r[2] for r in rows if len(r) >= 3]
    return descs


def load_best_model(workdir: Path) -> "pycolmap.Reconstruction":
    """Load the sparse model with the most images (COLMAP writes one model at
    sparse/, several as sparse/0, sparse/1, ...)."""
    sparse = workdir / "sparse"
    model_dirs = [sparse]
    if sparse.is_dir():
        model_dirs += sorted(sparse.glob("[0-9]*"), key=lambda p: int(p.name))
    best, best_imgs = None, -1
    for d in model_dirs:
        if not (d / "cameras.bin").exists():
            continue
        recon = pycolmap.Reconstruction(str(d))
        if recon.num_images() > best_imgs:
            best, best_imgs = recon, recon.num_images()
    if best is None:
        raise FileNotFoundError(f"no COLMAP sparse model found under {sparse}")
    return best


def build_map_file(workdir: Path, features_dir: Path, out: Path,
                   exclude=()) -> dict:
    """Write map.txt; returns a summary dict for the quality report."""
    recon = load_best_model(workdir)
    if recon.num_cameras() != 1:
        raise RuntimeError(f"expected exactly 1 camera, found {recon.num_cameras()}")
    cam = list(recon.cameras.values())[0]

    descs = load_descriptors(features_dir)
    exclude = {Path(e).name for e in exclude}

    # ---- map points: dedupe (image, feature_idx) observations by 3D position
    points = {}  # (rounded x,y,z) -> (x, y, z, hex_desc)
    skipped = {"missing_desc": 0, "empty_desc": 0, "excluded": 0}
    with open(workdir / "positions.csv", newline="") as f:
        for r in csv_mod.reader(f):
            if len(r) < 5 or r[0] == "image":
                continue
            img_name, feat_idx, x, y, z = r[0], int(r[1]), float(r[2]), float(r[3]), float(r[4])
            if Path(img_name).name in exclude:
                skipped["excluded"] += 1
                continue
            stem = Path(img_name).stem
            if stem not in descs or feat_idx >= len(descs[stem]):
                skipped["missing_desc"] += 1
                continue
            hexd = descs[stem][feat_idx]
            if all(c == "0" for c in hexd):
                skipped["empty_desc"] += 1
                continue
            key = (round(x, 4), round(y, 4), round(z, 4))
            points.setdefault(key, (x, y, z, hexd))

    with open(out, "w") as f:
        f.write("# localization map generated by vo-box write_map.py\n")
        f.write("# camera model + params (refined by COLMAP bundle adjustment)\n")
        f.write(f"CAMERA {cam.model_name} " +
                " ".join(f"{p:.10g}" for p in cam.params) + "\n")
        f.write("# reference world-to-camera poses (quaternion x y z w, translation x y z)\n")
        for im in recon.images.values():
            if not im.has_pose:
                continue
            q = im.cam_from_world().rotation.quat  # xyzw quaternion
            t = im.cam_from_world().translation
            f.write(f"POSE {im.name} "
                    f"{q[0]:.10g} {q[1]:.10g} {q[2]:.10g} {q[3]:.10g} "
                    f"{t[0]:.10g} {t[1]:.10g} {t[2]:.10g}\n")
        f.write("# map points: world x y z, 64-hex-char rBRIEF descriptor\n")
        for (x, y, z, hexd) in points.values():
            f.write(f"POINT {x:.10g} {y:.10g} {z:.10g} {hexd}\n")

    # Reprojection-error stats over the model's 3D points (per-point mean
    # error tracked during bundle adjustment).
    errs = [p.error for p in recon.points3D.values() if p.has_error]
    summary = {
        "camera_model": cam.model_name,
        "camera_params": list(map(float, cam.params)),
        "n_images": recon.num_images(),
        "n_points3d": recon.num_points3D(),
        "n_map_points": len(points),
        "skipped": skipped,
        "point_reproj_err": (None if not errs else
                             {"mean": float(np.mean(errs)),
                              "median": float(np.median(errs)),
                              "p95": float(np.percentile(errs, 95))}),
    }
    print(f"wrote {out}: {cam.model_name} camera {cam.params}, "
          f"{recon.num_images()} reference poses, {len(points)} map points "
          f"(skipped {skipped})")
    return summary


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--workdir", default="colmap_work")
    ap.add_argument("--features", default="grey-features")
    ap.add_argument("--out", default="map.txt")
    ap.add_argument("--exclude", action="append", default=[],
                    help="image name(s) whose observations are excluded (repeatable)")
    args = ap.parse_args()
    build_map_file(Path(args.workdir), Path(args.features), Path(args.out),
                   exclude=args.exclude)


if __name__ == "__main__":
    main()
