#!/usr/bin/env python3
"""Write map.txt from a COLMAP run (adapted from slam-exp build_map.py):
CAMERA line with the refined SIMPLE_RADIAL params (f cx cy k1), then one FRAME
group per registered image that has a calc8 embedding and >= min_points
triangulated features: `FRAME <image> <1064-hex embedding>` followed by its
`POINT x y z <64-hex rBRIEF>` lines."""

import argparse
import csv as csv_mod
from pathlib import Path

import numpy as np
import pycolmap

MIN_FRAME_POINTS = 8  # PnP needs >= 8; frames below this can never localize


def load_descriptors(features_dir: Path):
    """stem -> list of 64-char hex descriptor strings (row order = feature idx)."""
    descs = {}
    for csv_path in sorted(features_dir.glob("*.csv")):
        with open(csv_path) as f:
            rows = [[c.strip() for c in r] for r in csv_mod.reader(f) if r]
        descs[csv_path.stem] = [r[2] for r in rows if len(r) >= 3]
    return descs


def load_best_model(workdir: Path) -> "pycolmap.Reconstruction":
    """Load the sparse model with the most images (COLMAP writes one model at
    sparse/, several as sparse/0, sparse/1, ...)."""
    sparse = workdir / "sparse"
    # `best` is written by reconstruct_feature_positions (largest model); prefer
    # it on ties so the camera always matches the points it was built with.
    model_dirs = [sparse / "best", sparse]
    if sparse.is_dir():
        model_dirs += sorted(sparse.glob("[0-9]*"), key=lambda p: int(p.name))
    best, best_imgs = None, -1
    for d in model_dirs:
        if not (d / "cameras.bin").exists():
            continue
        recon = pycolmap.Reconstruction(str(d))
        if recon.num_images() > best_imgs:
            best, best_imgs = recon, recon.num_images()
    if best is None:
        raise FileNotFoundError(f"no COLMAP sparse model found under {sparse}")
    return best


def collect_frame_points(workdir: Path, features_dir: Path, exclude=()):
    """-> ({stem: [(x, y, z, hex_desc), ...]}, skipped). One entry per
    COLMAP-triangulated (image, feature) observation, grouped by image; empty
    descriptors are dropped. Frames COLMAP never registered are absent."""
    descs = load_descriptors(features_dir)
    exclude = {Path(e).stem for e in exclude}
    frames: dict = {}
    skipped = {"missing_desc": 0, "empty_desc": 0, "excluded": 0}
    with open(workdir / "positions.csv", newline="") as f:
        for r in csv_mod.reader(f):
            if len(r) < 5 or r[0] == "image":
                continue
            img_name, feat_idx, x, y, z = r[0], int(r[1]), float(r[2]), float(r[3]), float(r[4])
            stem = Path(img_name).stem
            if stem in exclude:
                skipped["excluded"] += 1
                continue
            if stem not in descs or feat_idx >= len(descs[stem]):
                skipped["missing_desc"] += 1
                continue
            hexd = descs[stem][feat_idx]
            if all(c == "0" for c in hexd):
                skipped["empty_desc"] += 1
                continue
            frames.setdefault(stem, []).append((x, y, z, hexd))
    return frames, skipped


def build_map_file(workdir: Path, features_dir: Path, out: Path,
                   embeddings: dict, min_points: int = MIN_FRAME_POINTS,
                   exclude=()) -> dict:
    """Write map.txt (CAMERA + FRAME groups) and return a summary dict.
    `embeddings` maps image stem -> 1064-byte calc8 descriptor."""
    recon = load_best_model(workdir)
    if recon.num_cameras() != 1:
        raise RuntimeError(f"expected exactly 1 camera, found {recon.num_cameras()}")
    cam = list(recon.cameras.values())[0]

    frames, skipped = collect_frame_points(workdir, features_dir, exclude)
    below = [s for s, p in frames.items() if len(p) < min_points]
    no_emb = [s for s, p in frames.items() if len(p) >= min_points and s not in embeddings]
    kept = {s: p for s, p in frames.items()
            if len(p) >= min_points and s in embeddings}

    with open(out, "w") as f:
        f.write("# localization map generated by vo-box write_map.py\n")
        f.write("# camera model + params (refined by COLMAP bundle adjustment)\n")
        f.write(f"CAMERA {cam.model_name} " +
                " ".join(f"{p:.10g}" for p in cam.params) + "\n")
        f.write("# FRAME <image> <1064-byte calc8 embedding, hex>\n")
        f.write("# POINT x y z <64-hex-char rBRIEF descriptor>, under its FRAME\n")
        for stem in sorted(kept):
            f.write(f"FRAME {stem} {embeddings[stem].hex()}\n")
            for (x, y, z, hexd) in kept[stem]:
                f.write(f"POINT {x:.10g} {y:.10g} {z:.10g} {hexd}\n")

    # Reprojection-error stats over the model's 3D points (per-point mean
    # error tracked during bundle adjustment).
    errs = [p.error for p in recon.points3D.values() if p.has_error]
    summary = {
        "camera_model": cam.model_name,
        "camera_params": list(map(float, cam.params)),
        "n_images": recon.num_images(),
        "n_points3d": recon.num_points3D(),
        "n_frames": len(kept),
        "n_map_points": sum(len(p) for p in kept.values()),
        "skipped": {**skipped, "below_min_points": len(below),
                    "no_embedding": len(no_emb)},
        "point_reproj_err": (None if not errs else
                             {"mean": float(np.mean(errs)),
                              "median": float(np.median(errs)),
                              "p95": float(np.percentile(errs, 95))}),
    }
    print(f"wrote {out}: {cam.model_name} camera {cam.params}, "
          f"{recon.num_images()} registered images, {summary['n_frames']} frames, "
          f"{summary['n_map_points']} map points (skipped {summary['skipped']})")
    return summary


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--workdir", default="colmap_work")
    ap.add_argument("--features", default="grey-features")
    ap.add_argument("--embeddings", default="embeddings",
                    help="dir of per-frame .npy embeddings (from embed_host.py)")
    ap.add_argument("--out", default="map.txt")
    ap.add_argument("--min-points", type=int, default=MIN_FRAME_POINTS)
    ap.add_argument("--exclude", action="append", default=[],
                    help="image name(s) whose observations are excluded (repeatable)")
    args = ap.parse_args()

    import embed_host
    embs = embed_host.load_embeddings_dir(args.embeddings)
    build_map_file(Path(args.workdir), Path(args.features), Path(args.out),
                   embeddings=embs, min_points=args.min_points,
                   exclude=args.exclude)


if __name__ == "__main__":
    main()
