/* fast12_trees.rs -- GENERATED by gen_fast12_scalar.py, do not edit.
 * Regenerate: python3 scripts/gen_fast12_scalar.py -o src/fast12_trees.rs
 * Naive 16-pixel FAST-12 ID3 trees, no cardinal/SIMD priors; included by src/fast.rs. */

/// (dx, dy) circle offsets, fast.c make_offsets() order (offset = dx + dy*stride).
pub const CIRCLE: [(i32, i32); 16] = [
    (0, 3), (1, 3), (2, 2), (3, 1), (3, 0), (3, -1), (2, -2), (1, -3), (0, -3), (-1, -3), (-2, -2), (-3, -1), (-3, 0), (-3, 1), (-2, 2), (-1, 3),
];

/// Light: 12 contiguous circle px strictly > thr (thr = center + b).
#[inline(always)]
pub fn light(p: &[u8], c: isize, off: &[isize; 16], thr: i32) -> bool {
    if (p[(c + off[0]) as usize] as i32) > thr {
        if (p[(c + off[1]) as usize] as i32) > thr {
            if (p[(c + off[2]) as usize] as i32) > thr {
                if (p[(c + off[3]) as usize] as i32) > thr {
                    if (p[(c + off[4]) as usize] as i32) > thr {
                        if (p[(c + off[5]) as usize] as i32) > thr {
                            if (p[(c + off[6]) as usize] as i32) > thr {
                                if (p[(c + off[7]) as usize] as i32) > thr {
                                    if (p[(c + off[8]) as usize] as i32) > thr {
                                        if (p[(c + off[9]) as usize] as i32) > thr {
                                            if (p[(c + off[10]) as usize] as i32) > thr {
                                                if (p[(c + off[11]) as usize] as i32) > thr {
                                                    return true;
                                                } else {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                }
                                            } else {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            }
                                        } else {
                                            if (p[(c + off[13]) as usize] as i32) > thr {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        }
                                    } else {
                                        if (p[(c + off[12]) as usize] as i32) > thr {
                                            if (p[(c + off[13]) as usize] as i32) > thr {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    }
                                } else {
                                    if (p[(c + off[11]) as usize] as i32) > thr {
                                        if (p[(c + off[12]) as usize] as i32) > thr {
                                            if (p[(c + off[13]) as usize] as i32) > thr {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                }
                            } else {
                                if (p[(c + off[10]) as usize] as i32) > thr {
                                    if (p[(c + off[11]) as usize] as i32) > thr {
                                        if (p[(c + off[12]) as usize] as i32) > thr {
                                            if (p[(c + off[13]) as usize] as i32) > thr {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            }
                        } else {
                            if (p[(c + off[9]) as usize] as i32) > thr {
                                if (p[(c + off[10]) as usize] as i32) > thr {
                                    if (p[(c + off[11]) as usize] as i32) > thr {
                                        if (p[(c + off[12]) as usize] as i32) > thr {
                                            if (p[(c + off[13]) as usize] as i32) > thr {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        }
                    } else {
                        if (p[(c + off[8]) as usize] as i32) > thr {
                            if (p[(c + off[9]) as usize] as i32) > thr {
                                if (p[(c + off[10]) as usize] as i32) > thr {
                                    if (p[(c + off[11]) as usize] as i32) > thr {
                                        if (p[(c + off[12]) as usize] as i32) > thr {
                                            if (p[(c + off[13]) as usize] as i32) > thr {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    }
                } else {
                    if (p[(c + off[7]) as usize] as i32) > thr {
                        if (p[(c + off[8]) as usize] as i32) > thr {
                            if (p[(c + off[9]) as usize] as i32) > thr {
                                if (p[(c + off[10]) as usize] as i32) > thr {
                                    if (p[(c + off[11]) as usize] as i32) > thr {
                                        if (p[(c + off[12]) as usize] as i32) > thr {
                                            if (p[(c + off[13]) as usize] as i32) > thr {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                }
            } else {
                if (p[(c + off[6]) as usize] as i32) > thr {
                    if (p[(c + off[7]) as usize] as i32) > thr {
                        if (p[(c + off[8]) as usize] as i32) > thr {
                            if (p[(c + off[9]) as usize] as i32) > thr {
                                if (p[(c + off[10]) as usize] as i32) > thr {
                                    if (p[(c + off[11]) as usize] as i32) > thr {
                                        if (p[(c + off[12]) as usize] as i32) > thr {
                                            if (p[(c + off[13]) as usize] as i32) > thr {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        if (p[(c + off[3]) as usize] as i32) > thr {
                                                            if (p[(c + off[4]) as usize] as i32) > thr {
                                                                if (p[(c + off[5]) as usize] as i32) > thr {
                                                                    return true;
                                                                } else {
                                                                    return false;
                                                                }
                                                            } else {
                                                                return false;
                                                            }
                                                        } else {
                                                            return false;
                                                        }
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            }
        } else {
            if (p[(c + off[5]) as usize] as i32) > thr {
                if (p[(c + off[6]) as usize] as i32) > thr {
                    if (p[(c + off[7]) as usize] as i32) > thr {
                        if (p[(c + off[8]) as usize] as i32) > thr {
                            if (p[(c + off[9]) as usize] as i32) > thr {
                                if (p[(c + off[10]) as usize] as i32) > thr {
                                    if (p[(c + off[11]) as usize] as i32) > thr {
                                        if (p[(c + off[12]) as usize] as i32) > thr {
                                            if (p[(c + off[13]) as usize] as i32) > thr {
                                                if (p[(c + off[14]) as usize] as i32) > thr {
                                                    if (p[(c + off[15]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        if (p[(c + off[3]) as usize] as i32) > thr {
                                                            if (p[(c + off[4]) as usize] as i32) > thr {
                                                                return true;
                                                            } else {
                                                                return false;
                                                            }
                                                        } else {
                                                            return false;
                                                        }
                                                    }
                                                } else {
                                                    if (p[(c + off[2]) as usize] as i32) > thr {
                                                        if (p[(c + off[3]) as usize] as i32) > thr {
                                                            if (p[(c + off[4]) as usize] as i32) > thr {
                                                                return true;
                                                            } else {
                                                                return false;
                                                            }
                                                        } else {
                                                            return false;
                                                        }
                                                    } else {
                                                        return false;
                                                    }
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                return false;
            }
        }
    } else {
        if (p[(c + off[4]) as usize] as i32) > thr {
            if (p[(c + off[5]) as usize] as i32) > thr {
                if (p[(c + off[6]) as usize] as i32) > thr {
                    if (p[(c + off[7]) as usize] as i32) > thr {
                        if (p[(c + off[8]) as usize] as i32) > thr {
                            if (p[(c + off[9]) as usize] as i32) > thr {
                                if (p[(c + off[10]) as usize] as i32) > thr {
                                    if (p[(c + off[11]) as usize] as i32) > thr {
                                        if (p[(c + off[12]) as usize] as i32) > thr {
                                            if (p[(c + off[3]) as usize] as i32) > thr {
                                                if (p[(c + off[2]) as usize] as i32) > thr {
                                                    if (p[(c + off[1]) as usize] as i32) > thr {
                                                        return true;
                                                    } else {
                                                        if (p[(c + off[13]) as usize] as i32) > thr {
                                                            return true;
                                                        } else {
                                                            return false;
                                                        }
                                                    }
                                                } else {
                                                    if (p[(c + off[13]) as usize] as i32) > thr {
                                                        if (p[(c + off[14]) as usize] as i32) > thr {
                                                            return true;
                                                        } else {
                                                            return false;
                                                        }
                                                    } else {
                                                        return false;
                                                    }
                                                }
                                            } else {
                                                if (p[(c + off[13]) as usize] as i32) > thr {
                                                    if (p[(c + off[14]) as usize] as i32) > thr {
                                                        if (p[(c + off[15]) as usize] as i32) > thr {
                                                            return true;
                                                        } else {
                                                            return false;
                                                        }
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
}

/// Dark: light's mirror, strictly < thr (thr = center - b).
#[inline(always)]
pub fn dark(p: &[u8], c: isize, off: &[isize; 16], thr: i32) -> bool {
    if (p[(c + off[0]) as usize] as i32) < thr {
        if (p[(c + off[1]) as usize] as i32) < thr {
            if (p[(c + off[2]) as usize] as i32) < thr {
                if (p[(c + off[3]) as usize] as i32) < thr {
                    if (p[(c + off[4]) as usize] as i32) < thr {
                        if (p[(c + off[5]) as usize] as i32) < thr {
                            if (p[(c + off[6]) as usize] as i32) < thr {
                                if (p[(c + off[7]) as usize] as i32) < thr {
                                    if (p[(c + off[8]) as usize] as i32) < thr {
                                        if (p[(c + off[9]) as usize] as i32) < thr {
                                            if (p[(c + off[10]) as usize] as i32) < thr {
                                                if (p[(c + off[11]) as usize] as i32) < thr {
                                                    return true;
                                                } else {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                }
                                            } else {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            }
                                        } else {
                                            if (p[(c + off[13]) as usize] as i32) < thr {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        }
                                    } else {
                                        if (p[(c + off[12]) as usize] as i32) < thr {
                                            if (p[(c + off[13]) as usize] as i32) < thr {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    }
                                } else {
                                    if (p[(c + off[11]) as usize] as i32) < thr {
                                        if (p[(c + off[12]) as usize] as i32) < thr {
                                            if (p[(c + off[13]) as usize] as i32) < thr {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                }
                            } else {
                                if (p[(c + off[10]) as usize] as i32) < thr {
                                    if (p[(c + off[11]) as usize] as i32) < thr {
                                        if (p[(c + off[12]) as usize] as i32) < thr {
                                            if (p[(c + off[13]) as usize] as i32) < thr {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            }
                        } else {
                            if (p[(c + off[9]) as usize] as i32) < thr {
                                if (p[(c + off[10]) as usize] as i32) < thr {
                                    if (p[(c + off[11]) as usize] as i32) < thr {
                                        if (p[(c + off[12]) as usize] as i32) < thr {
                                            if (p[(c + off[13]) as usize] as i32) < thr {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        }
                    } else {
                        if (p[(c + off[8]) as usize] as i32) < thr {
                            if (p[(c + off[9]) as usize] as i32) < thr {
                                if (p[(c + off[10]) as usize] as i32) < thr {
                                    if (p[(c + off[11]) as usize] as i32) < thr {
                                        if (p[(c + off[12]) as usize] as i32) < thr {
                                            if (p[(c + off[13]) as usize] as i32) < thr {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    }
                } else {
                    if (p[(c + off[7]) as usize] as i32) < thr {
                        if (p[(c + off[8]) as usize] as i32) < thr {
                            if (p[(c + off[9]) as usize] as i32) < thr {
                                if (p[(c + off[10]) as usize] as i32) < thr {
                                    if (p[(c + off[11]) as usize] as i32) < thr {
                                        if (p[(c + off[12]) as usize] as i32) < thr {
                                            if (p[(c + off[13]) as usize] as i32) < thr {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                }
            } else {
                if (p[(c + off[6]) as usize] as i32) < thr {
                    if (p[(c + off[7]) as usize] as i32) < thr {
                        if (p[(c + off[8]) as usize] as i32) < thr {
                            if (p[(c + off[9]) as usize] as i32) < thr {
                                if (p[(c + off[10]) as usize] as i32) < thr {
                                    if (p[(c + off[11]) as usize] as i32) < thr {
                                        if (p[(c + off[12]) as usize] as i32) < thr {
                                            if (p[(c + off[13]) as usize] as i32) < thr {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        if (p[(c + off[3]) as usize] as i32) < thr {
                                                            if (p[(c + off[4]) as usize] as i32) < thr {
                                                                if (p[(c + off[5]) as usize] as i32) < thr {
                                                                    return true;
                                                                } else {
                                                                    return false;
                                                                }
                                                            } else {
                                                                return false;
                                                            }
                                                        } else {
                                                            return false;
                                                        }
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            }
        } else {
            if (p[(c + off[5]) as usize] as i32) < thr {
                if (p[(c + off[6]) as usize] as i32) < thr {
                    if (p[(c + off[7]) as usize] as i32) < thr {
                        if (p[(c + off[8]) as usize] as i32) < thr {
                            if (p[(c + off[9]) as usize] as i32) < thr {
                                if (p[(c + off[10]) as usize] as i32) < thr {
                                    if (p[(c + off[11]) as usize] as i32) < thr {
                                        if (p[(c + off[12]) as usize] as i32) < thr {
                                            if (p[(c + off[13]) as usize] as i32) < thr {
                                                if (p[(c + off[14]) as usize] as i32) < thr {
                                                    if (p[(c + off[15]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        if (p[(c + off[3]) as usize] as i32) < thr {
                                                            if (p[(c + off[4]) as usize] as i32) < thr {
                                                                return true;
                                                            } else {
                                                                return false;
                                                            }
                                                        } else {
                                                            return false;
                                                        }
                                                    }
                                                } else {
                                                    if (p[(c + off[2]) as usize] as i32) < thr {
                                                        if (p[(c + off[3]) as usize] as i32) < thr {
                                                            if (p[(c + off[4]) as usize] as i32) < thr {
                                                                return true;
                                                            } else {
                                                                return false;
                                                            }
                                                        } else {
                                                            return false;
                                                        }
                                                    } else {
                                                        return false;
                                                    }
                                                }
                                            } else {
                                                return false;
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                return false;
            }
        }
    } else {
        if (p[(c + off[4]) as usize] as i32) < thr {
            if (p[(c + off[5]) as usize] as i32) < thr {
                if (p[(c + off[6]) as usize] as i32) < thr {
                    if (p[(c + off[7]) as usize] as i32) < thr {
                        if (p[(c + off[8]) as usize] as i32) < thr {
                            if (p[(c + off[9]) as usize] as i32) < thr {
                                if (p[(c + off[10]) as usize] as i32) < thr {
                                    if (p[(c + off[11]) as usize] as i32) < thr {
                                        if (p[(c + off[12]) as usize] as i32) < thr {
                                            if (p[(c + off[3]) as usize] as i32) < thr {
                                                if (p[(c + off[2]) as usize] as i32) < thr {
                                                    if (p[(c + off[1]) as usize] as i32) < thr {
                                                        return true;
                                                    } else {
                                                        if (p[(c + off[13]) as usize] as i32) < thr {
                                                            return true;
                                                        } else {
                                                            return false;
                                                        }
                                                    }
                                                } else {
                                                    if (p[(c + off[13]) as usize] as i32) < thr {
                                                        if (p[(c + off[14]) as usize] as i32) < thr {
                                                            return true;
                                                        } else {
                                                            return false;
                                                        }
                                                    } else {
                                                        return false;
                                                    }
                                                }
                                            } else {
                                                if (p[(c + off[13]) as usize] as i32) < thr {
                                                    if (p[(c + off[14]) as usize] as i32) < thr {
                                                        if (p[(c + off[15]) as usize] as i32) < thr {
                                                            return true;
                                                        } else {
                                                            return false;
                                                        }
                                                    } else {
                                                        return false;
                                                    }
                                                } else {
                                                    return false;
                                                }
                                            }
                                        } else {
                                            return false;
                                        }
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
}
